def isEven(number):
    if number == 1: return False
    elif number == 2: return True
    elif number == 3: return False
    elif number == 4: return True
    elif number == 5: return False
    elif number == 6: return True
    elif number == 7: return False
    elif number == 8: return True
    elif number == 9: return False
    elif number == 10: return True
    elif number == 11: return False
    elif number == 12: return True
    elif number == 13: return False
    elif number == 14: return True
    elif number == 15: return False
    elif number == 16: return True
    elif number == 17: return False
    elif number == 18: return True
    elif number == 19: return False
    elif number == 20: return True
    elif number == 21: return False
    elif number == 22: return True
    elif number == 23: return False
    elif number == 24: return True
    elif number == 25: return False
    elif number == 26: return True
    elif number == 27: return False
    elif number == 28: return True
    elif number == 29: return False
    elif number == 30: return True
    elif number == 31: return False
    elif number == 32: return True
    elif number == 33: return False
    elif number == 34: return True
    elif number == 35: return False
    elif number == 36: return True
    elif number == 37: return False
    elif number == 38: return True
    elif number == 39: return False
    elif number == 40: return True
    elif number == 41: return False
    elif number == 42: return True
    elif number == 43: return False
    elif number == 44: return True
    elif number == 45: return False
    elif number == 46: return True
    elif number == 47: return False
    elif number == 48: return True
    elif number == 49: return False
    elif number == 50: return True
    elif number == 51: return False
    elif number == 52: return True
    elif number == 53: return False
    elif number == 54: return True
    elif number == 55: return False
    elif number == 56: return True
    elif number == 57: return False
    elif number == 58: return True
    elif number == 59: return False
    elif number == 60: return True
    elif number == 61: return False
    elif number == 62: return True
    elif number == 63: return False
    elif number == 64: return True
    elif number == 65: return False
    elif number == 66: return True
    elif number == 67: return False
    elif number == 68: return True
    elif number == 69: return False
    elif number == 70: return True
    elif number == 71: return False
    elif number == 72: return True
    elif number == 73: return False
    elif number == 74: return True
    elif number == 75: return False
    elif number == 76: return True
    elif number == 77: return False
    elif number == 78: return True
    elif number == 79: return False
    elif number == 80: return True
    elif number == 81: return False
    elif number == 82: return True
    elif number == 83: return False
    elif number == 84: return True
    elif number == 85: return False
    elif number == 86: return True
    elif number == 87: return False
    elif number == 88: return True
    elif number == 89: return False
    elif number == 90: return True
    elif number == 91: return False
    elif number == 92: return True
    elif number == 93: return False
    elif number == 94: return True
    elif number == 95: return False
    elif number == 96: return True
    elif number == 97: return False
    elif number == 98: return True
    elif number == 99: return False
    elif number == 100: return True
    elif number == 101: return False
    elif number == 102: return True
    elif number == 103: return False
    elif number == 104: return True
    elif number == 105: return False
    elif number == 106: return True
    elif number == 107: return False
    elif number == 108: return True
    elif number == 109: return False
    elif number == 110: return True
    elif number == 111: return False
    elif number == 112: return True
    elif number == 113: return False
    elif number == 114: return True
    elif number == 115: return False
    elif number == 116: return True
    elif number == 117: return False
    elif number == 118: return True
    elif number == 119: return False
    elif number == 120: return True
    elif number == 121: return False
    elif number == 122: return True
    elif number == 123: return False
    elif number == 124: return True
    elif number == 125: return False
    elif number == 126: return True
    elif number == 127: return False
    elif number == 128: return True
    elif number == 129: return False
    elif number == 130: return True
    elif number == 131: return False
    elif number == 132: return True
    elif number == 133: return False
    elif number == 134: return True
    elif number == 135: return False
    elif number == 136: return True
    elif number == 137: return False
    elif number == 138: return True
    elif number == 139: return False
    elif number == 140: return True
    elif number == 141: return False
    elif number == 142: return True
    elif number == 143: return False
    elif number == 144: return True
    elif number == 145: return False
    elif number == 146: return True
    elif number == 147: return False
    elif number == 148: return True
    elif number == 149: return False
    elif number == 150: return True
    elif number == 151: return False
    elif number == 152: return True
    elif number == 153: return False
    elif number == 154: return True
    elif number == 155: return False
    elif number == 156: return True
    elif number == 157: return False
    elif number == 158: return True
    elif number == 159: return False
    elif number == 160: return True
    elif number == 161: return False
    elif number == 162: return True
    elif number == 163: return False
    elif number == 164: return True
    elif number == 165: return False
    elif number == 166: return True
    elif number == 167: return False
    elif number == 168: return True
    elif number == 169: return False
    elif number == 170: return True
    elif number == 171: return False
    elif number == 172: return True
    elif number == 173: return False
    elif number == 174: return True
    elif number == 175: return False
    elif number == 176: return True
    elif number == 177: return False
    elif number == 178: return True
    elif number == 179: return False
    elif number == 180: return True
    elif number == 181: return False
    elif number == 182: return True
    elif number == 183: return False
    elif number == 184: return True
    elif number == 185: return False
    elif number == 186: return True
    elif number == 187: return False
    elif number == 188: return True
    elif number == 189: return False
    elif number == 190: return True
    elif number == 191: return False
    elif number == 192: return True
    elif number == 193: return False
    elif number == 194: return True
    elif number == 195: return False
    elif number == 196: return True
    elif number == 197: return False
    elif number == 198: return True
    elif number == 199: return False
    elif number == 200: return True
    elif number == 201: return False
    elif number == 202: return True
    elif number == 203: return False
    elif number == 204: return True
    elif number == 205: return False
    elif number == 206: return True
    elif number == 207: return False
    elif number == 208: return True
    elif number == 209: return False
    elif number == 210: return True
    elif number == 211: return False
    elif number == 212: return True
    elif number == 213: return False
    elif number == 214: return True
    elif number == 215: return False
    elif number == 216: return True
    elif number == 217: return False
    elif number == 218: return True
    elif number == 219: return False
    elif number == 220: return True
    elif number == 221: return False
    elif number == 222: return True
    elif number == 223: return False
    elif number == 224: return True
    elif number == 225: return False
    elif number == 226: return True
    elif number == 227: return False
    elif number == 228: return True
    elif number == 229: return False
    elif number == 230: return True
    elif number == 231: return False
    elif number == 232: return True
    elif number == 233: return False
    elif number == 234: return True
    elif number == 235: return False
    elif number == 236: return True
    elif number == 237: return False
    elif number == 238: return True
    elif number == 239: return False
    elif number == 240: return True
    elif number == 241: return False
    elif number == 242: return True
    elif number == 243: return False
    elif number == 244: return True
    elif number == 245: return False
    elif number == 246: return True
    elif number == 247: return False
    elif number == 248: return True
    elif number == 249: return False
    elif number == 250: return True
    elif number == 251: return False
    elif number == 252: return True
    elif number == 253: return False
    elif number == 254: return True
    elif number == 255: return False
    elif number == 256: return True
    elif number == 257: return False
    elif number == 258: return True
    elif number == 259: return False
    elif number == 260: return True
    elif number == 261: return False
    elif number == 262: return True
    elif number == 263: return False
    elif number == 264: return True
    elif number == 265: return False
    elif number == 266: return True
    elif number == 267: return False
    elif number == 268: return True
    elif number == 269: return False
    elif number == 270: return True
    elif number == 271: return False
    elif number == 272: return True
    elif number == 273: return False
    elif number == 274: return True
    elif number == 275: return False
    elif number == 276: return True
    elif number == 277: return False
    elif number == 278: return True
    elif number == 279: return False
    elif number == 280: return True
    elif number == 281: return False
    elif number == 282: return True
    elif number == 283: return False
    elif number == 284: return True
    elif number == 285: return False
    elif number == 286: return True
    elif number == 287: return False
    elif number == 288: return True
    elif number == 289: return False
    elif number == 290: return True
    elif number == 291: return False
    elif number == 292: return True
    elif number == 293: return False
    elif number == 294: return True
    elif number == 295: return False
    elif number == 296: return True
    elif number == 297: return False
    elif number == 298: return True
    elif number == 299: return False
    elif number == 300: return True
    elif number == 301: return False
    elif number == 302: return True
    elif number == 303: return False
    elif number == 304: return True
    elif number == 305: return False
    elif number == 306: return True
    elif number == 307: return False
    elif number == 308: return True
    elif number == 309: return False
    elif number == 310: return True
    elif number == 311: return False
    elif number == 312: return True
    elif number == 313: return False
    elif number == 314: return True
    elif number == 315: return False
    elif number == 316: return True
    elif number == 317: return False
    elif number == 318: return True
    elif number == 319: return False
    elif number == 320: return True
    elif number == 321: return False
    elif number == 322: return True
    elif number == 323: return False
    elif number == 324: return True
    elif number == 325: return False
    elif number == 326: return True
    elif number == 327: return False
    elif number == 328: return True
    elif number == 329: return False
    elif number == 330: return True
    elif number == 331: return False
    elif number == 332: return True
    elif number == 333: return False
    elif number == 334: return True
    elif number == 335: return False
    elif number == 336: return True
    elif number == 337: return False
    elif number == 338: return True
    elif number == 339: return False
    elif number == 340: return True
    elif number == 341: return False
    elif number == 342: return True
    elif number == 343: return False
    elif number == 344: return True
    elif number == 345: return False
    elif number == 346: return True
    elif number == 347: return False
    elif number == 348: return True
    elif number == 349: return False
    elif number == 350: return True
    elif number == 351: return False
    elif number == 352: return True
    elif number == 353: return False
    elif number == 354: return True
    elif number == 355: return False
    elif number == 356: return True
    elif number == 357: return False
    elif number == 358: return True
    elif number == 359: return False
    elif number == 360: return True
    elif number == 361: return False
    elif number == 362: return True
    elif number == 363: return False
    elif number == 364: return True
    elif number == 365: return False
    elif number == 366: return True
    elif number == 367: return False
    elif number == 368: return True
    elif number == 369: return False
    elif number == 370: return True
    elif number == 371: return False
    elif number == 372: return True
    elif number == 373: return False
    elif number == 374: return True
    elif number == 375: return False
    elif number == 376: return True
    elif number == 377: return False
    elif number == 378: return True
    elif number == 379: return False
    elif number == 380: return True
    elif number == 381: return False
    elif number == 382: return True
    elif number == 383: return False
    elif number == 384: return True
    elif number == 385: return False
    elif number == 386: return True
    elif number == 387: return False
    elif number == 388: return True
    elif number == 389: return False
    elif number == 390: return True
    elif number == 391: return False
    elif number == 392: return True
    elif number == 393: return False
    elif number == 394: return True
    elif number == 395: return False
    elif number == 396: return True
    elif number == 397: return False
    elif number == 398: return True
    elif number == 399: return False
    elif number == 400: return True
    elif number == 401: return False
    elif number == 402: return True
    elif number == 403: return False
    elif number == 404: return True
    elif number == 405: return False
    elif number == 406: return True
    elif number == 407: return False
    elif number == 408: return True
    elif number == 409: return False
    elif number == 410: return True
    elif number == 411: return False
    elif number == 412: return True
    elif number == 413: return False
    elif number == 414: return True
    elif number == 415: return False
    elif number == 416: return True
    elif number == 417: return False
    elif number == 418: return True
    elif number == 419: return False
    elif number == 420: return True
    elif number == 421: return False
    elif number == 422: return True
    elif number == 423: return False
    elif number == 424: return True
    elif number == 425: return False
    elif number == 426: return True
    elif number == 427: return False
    elif number == 428: return True
    elif number == 429: return False
    elif number == 430: return True
    elif number == 431: return False
    elif number == 432: return True
    elif number == 433: return False
    elif number == 434: return True
    elif number == 435: return False
    elif number == 436: return True
    elif number == 437: return False
    elif number == 438: return True
    elif number == 439: return False
    elif number == 440: return True
    elif number == 441: return False
    elif number == 442: return True
    elif number == 443: return False
    elif number == 444: return True
    elif number == 445: return False
    elif number == 446: return True
    elif number == 447: return False
    elif number == 448: return True
    elif number == 449: return False
    elif number == 450: return True
    elif number == 451: return False
    elif number == 452: return True
    elif number == 453: return False
    elif number == 454: return True
    elif number == 455: return False
    elif number == 456: return True
    elif number == 457: return False
    elif number == 458: return True
    elif number == 459: return False
    elif number == 460: return True
    elif number == 461: return False
    elif number == 462: return True
    elif number == 463: return False
    elif number == 464: return True
    elif number == 465: return False
    elif number == 466: return True
    elif number == 467: return False
    elif number == 468: return True
    elif number == 469: return False
    elif number == 470: return True
    elif number == 471: return False
    elif number == 472: return True
    elif number == 473: return False
    elif number == 474: return True
    elif number == 475: return False
    elif number == 476: return True
    elif number == 477: return False
    elif number == 478: return True
    elif number == 479: return False
    elif number == 480: return True
    elif number == 481: return False
    elif number == 482: return True
    elif number == 483: return False
    elif number == 484: return True
    elif number == 485: return False
    elif number == 486: return True
    elif number == 487: return False
    elif number == 488: return True
    elif number == 489: return False
    elif number == 490: return True
    elif number == 491: return False
    elif number == 492: return True
    elif number == 493: return False
    elif number == 494: return True
    elif number == 495: return False
    elif number == 496: return True
    elif number == 497: return False
    elif number == 498: return True
    elif number == 499: return False
    elif number == 500: return True
    elif number == 501: return False
    elif number == 502: return True
    elif number == 503: return False
    elif number == 504: return True
    elif number == 505: return False
    elif number == 506: return True
    elif number == 507: return False
    elif number == 508: return True
    elif number == 509: return False
    elif number == 510: return True
    elif number == 511: return False
    elif number == 512: return True
    elif number == 513: return False
    elif number == 514: return True
    elif number == 515: return False
    elif number == 516: return True
    elif number == 517: return False
    elif number == 518: return True
    elif number == 519: return False
    elif number == 520: return True
    elif number == 521: return False
    elif number == 522: return True
    elif number == 523: return False
    elif number == 524: return True
    elif number == 525: return False
    elif number == 526: return True
    elif number == 527: return False
    elif number == 528: return True
    elif number == 529: return False
    elif number == 530: return True
    elif number == 531: return False
    elif number == 532: return True
    elif number == 533: return False
    elif number == 534: return True
    elif number == 535: return False
    elif number == 536: return True
    elif number == 537: return False
    elif number == 538: return True
    elif number == 539: return False
    elif number == 540: return True
    elif number == 541: return False
    elif number == 542: return True
    elif number == 543: return False
    elif number == 544: return True
    elif number == 545: return False
    elif number == 546: return True
    elif number == 547: return False
    elif number == 548: return True
    elif number == 549: return False
    elif number == 550: return True
    elif number == 551: return False
    elif number == 552: return True
    elif number == 553: return False
    elif number == 554: return True
    elif number == 555: return False
    elif number == 556: return True
    elif number == 557: return False
    elif number == 558: return True
    elif number == 559: return False
    elif number == 560: return True
    elif number == 561: return False
    elif number == 562: return True
    elif number == 563: return False
    elif number == 564: return True
    elif number == 565: return False
    elif number == 566: return True
    elif number == 567: return False
    elif number == 568: return True
    elif number == 569: return False
    elif number == 570: return True
    elif number == 571: return False
    elif number == 572: return True
    elif number == 573: return False
    elif number == 574: return True
    elif number == 575: return False
    elif number == 576: return True
    elif number == 577: return False
    elif number == 578: return True
    elif number == 579: return False
    elif number == 580: return True
    elif number == 581: return False
    elif number == 582: return True
    elif number == 583: return False
    elif number == 584: return True
    elif number == 585: return False
    elif number == 586: return True
    elif number == 587: return False
    elif number == 588: return True
    elif number == 589: return False
    elif number == 590: return True
    elif number == 591: return False
    elif number == 592: return True
    elif number == 593: return False
    elif number == 594: return True
    elif number == 595: return False
    elif number == 596: return True
    elif number == 597: return False
    elif number == 598: return True
    elif number == 599: return False
    elif number == 600: return True
    elif number == 601: return False
    elif number == 602: return True
    elif number == 603: return False
    elif number == 604: return True
    elif number == 605: return False
    elif number == 606: return True
    elif number == 607: return False
    elif number == 608: return True
    elif number == 609: return False
    elif number == 610: return True
    elif number == 611: return False
    elif number == 612: return True
    elif number == 613: return False
    elif number == 614: return True
    elif number == 615: return False
    elif number == 616: return True
    elif number == 617: return False
    elif number == 618: return True
    elif number == 619: return False
    elif number == 620: return True
    elif number == 621: return False
    elif number == 622: return True
    elif number == 623: return False
    elif number == 624: return True
    elif number == 625: return False
    elif number == 626: return True
    elif number == 627: return False
    elif number == 628: return True
    elif number == 629: return False
    elif number == 630: return True
    elif number == 631: return False
    elif number == 632: return True
    elif number == 633: return False
    elif number == 634: return True
    elif number == 635: return False
    elif number == 636: return True
    elif number == 637: return False
    elif number == 638: return True
    elif number == 639: return False
    elif number == 640: return True
    elif number == 641: return False
    elif number == 642: return True
    elif number == 643: return False
    elif number == 644: return True
    elif number == 645: return False
    elif number == 646: return True
    elif number == 647: return False
    elif number == 648: return True
    elif number == 649: return False
    elif number == 650: return True
    elif number == 651: return False
    elif number == 652: return True
    elif number == 653: return False
    elif number == 654: return True
    elif number == 655: return False
    elif number == 656: return True
    elif number == 657: return False
    elif number == 658: return True
    elif number == 659: return False
    elif number == 660: return True
    elif number == 661: return False
    elif number == 662: return True
    elif number == 663: return False
    elif number == 664: return True
    elif number == 665: return False
    elif number == 666: return True
    elif number == 667: return False
    elif number == 668: return True
    elif number == 669: return False
    elif number == 670: return True
    elif number == 671: return False
    elif number == 672: return True
    elif number == 673: return False
    elif number == 674: return True
    elif number == 675: return False
    elif number == 676: return True
    elif number == 677: return False
    elif number == 678: return True
    elif number == 679: return False
    elif number == 680: return True
    elif number == 681: return False
    elif number == 682: return True
    elif number == 683: return False
    elif number == 684: return True
    elif number == 685: return False
    elif number == 686: return True
    elif number == 687: return False
    elif number == 688: return True
    elif number == 689: return False
    elif number == 690: return True
    elif number == 691: return False
    elif number == 692: return True
    elif number == 693: return False
    elif number == 694: return True
    elif number == 695: return False
    elif number == 696: return True
    elif number == 697: return False
    elif number == 698: return True
    elif number == 699: return False
    elif number == 700: return True
    elif number == 701: return False
    elif number == 702: return True
    elif number == 703: return False
    elif number == 704: return True
    elif number == 705: return False
    elif number == 706: return True
    elif number == 707: return False
    elif number == 708: return True
    elif number == 709: return False
    elif number == 710: return True
    elif number == 711: return False
    elif number == 712: return True
    elif number == 713: return False
    elif number == 714: return True
    elif number == 715: return False
    elif number == 716: return True
    elif number == 717: return False
    elif number == 718: return True
    elif number == 719: return False
    elif number == 720: return True
    elif number == 721: return False
    elif number == 722: return True
    elif number == 723: return False
    elif number == 724: return True
    elif number == 725: return False
    elif number == 726: return True
    elif number == 727: return False
    elif number == 728: return True
    elif number == 729: return False
    elif number == 730: return True
    elif number == 731: return False
    elif number == 732: return True
    elif number == 733: return False
    elif number == 734: return True
    elif number == 735: return False
    elif number == 736: return True
    elif number == 737: return False
    elif number == 738: return True
    elif number == 739: return False
    elif number == 740: return True
    elif number == 741: return False
    elif number == 742: return True
    elif number == 743: return False
    elif number == 744: return True
    elif number == 745: return False
    elif number == 746: return True
    elif number == 747: return False
    elif number == 748: return True
    elif number == 749: return False
    elif number == 750: return True
    elif number == 751: return False
    elif number == 752: return True
    elif number == 753: return False
    elif number == 754: return True
    elif number == 755: return False
    elif number == 756: return True
    elif number == 757: return False
    elif number == 758: return True
    elif number == 759: return False
    elif number == 760: return True
    elif number == 761: return False
    elif number == 762: return True
    elif number == 763: return False
    elif number == 764: return True
    elif number == 765: return False
    elif number == 766: return True
    elif number == 767: return False
    elif number == 768: return True
    elif number == 769: return False
    elif number == 770: return True
    elif number == 771: return False
    elif number == 772: return True
    elif number == 773: return False
    elif number == 774: return True
    elif number == 775: return False
    elif number == 776: return True
    elif number == 777: return False
    elif number == 778: return True
    elif number == 779: return False
    elif number == 780: return True
    elif number == 781: return False
    elif number == 782: return True
    elif number == 783: return False
    elif number == 784: return True
    elif number == 785: return False
    elif number == 786: return True
    elif number == 787: return False
    elif number == 788: return True
    elif number == 789: return False
    elif number == 790: return True
    elif number == 791: return False
    elif number == 792: return True
    elif number == 793: return False
    elif number == 794: return True
    elif number == 795: return False
    elif number == 796: return True
    elif number == 797: return False
    elif number == 798: return True
    elif number == 799: return False
    elif number == 800: return True
    elif number == 801: return False
    elif number == 802: return True
    elif number == 803: return False
    elif number == 804: return True
    elif number == 805: return False
    elif number == 806: return True
    elif number == 807: return False
    elif number == 808: return True
    elif number == 809: return False
    elif number == 810: return True
    elif number == 811: return False
    elif number == 812: return True
    elif number == 813: return False
    elif number == 814: return True
    elif number == 815: return False
    elif number == 816: return True
    elif number == 817: return False
    elif number == 818: return True
    elif number == 819: return False
    elif number == 820: return True
    elif number == 821: return False
    elif number == 822: return True
    elif number == 823: return False
    elif number == 824: return True
    elif number == 825: return False
    elif number == 826: return True
    elif number == 827: return False
    elif number == 828: return True
    elif number == 829: return False
    elif number == 830: return True
    elif number == 831: return False
    elif number == 832: return True
    elif number == 833: return False
    elif number == 834: return True
    elif number == 835: return False
    elif number == 836: return True
    elif number == 837: return False
    elif number == 838: return True
    elif number == 839: return False
    elif number == 840: return True
    elif number == 841: return False
    elif number == 842: return True
    elif number == 843: return False
    elif number == 844: return True
    elif number == 845: return False
    elif number == 846: return True
    elif number == 847: return False
    elif number == 848: return True
    elif number == 849: return False
    elif number == 850: return True
    elif number == 851: return False
    elif number == 852: return True
    elif number == 853: return False
    elif number == 854: return True
    elif number == 855: return False
    elif number == 856: return True
    elif number == 857: return False
    elif number == 858: return True
    elif number == 859: return False
    elif number == 860: return True
    elif number == 861: return False
    elif number == 862: return True
    elif number == 863: return False
    elif number == 864: return True
    elif number == 865: return False
    elif number == 866: return True
    elif number == 867: return False
    elif number == 868: return True
    elif number == 869: return False
    elif number == 870: return True
    elif number == 871: return False
    elif number == 872: return True
    elif number == 873: return False
    elif number == 874: return True
    elif number == 875: return False
    elif number == 876: return True
    elif number == 877: return False
    elif number == 878: return True
    elif number == 879: return False
    elif number == 880: return True
    elif number == 881: return False
    elif number == 882: return True
    elif number == 883: return False
    elif number == 884: return True
    elif number == 885: return False
    elif number == 886: return True
    elif number == 887: return False
    elif number == 888: return True
    elif number == 889: return False
    elif number == 890: return True
    elif number == 891: return False
    elif number == 892: return True
    elif number == 893: return False
    elif number == 894: return True
    elif number == 895: return False
    elif number == 896: return True
    elif number == 897: return False
    elif number == 898: return True
    elif number == 899: return False
    elif number == 900: return True
    elif number == 901: return False
    elif number == 902: return True
    elif number == 903: return False
    elif number == 904: return True
    elif number == 905: return False
    elif number == 906: return True
    elif number == 907: return False
    elif number == 908: return True
    elif number == 909: return False
    elif number == 910: return True
    elif number == 911: return False
    elif number == 912: return True
    elif number == 913: return False
    elif number == 914: return True
    elif number == 915: return False
    elif number == 916: return True
    elif number == 917: return False
    elif number == 918: return True
    elif number == 919: return False
    elif number == 920: return True
    elif number == 921: return False
    elif number == 922: return True
    elif number == 923: return False
    elif number == 924: return True
    elif number == 925: return False
    elif number == 926: return True
    elif number == 927: return False
    elif number == 928: return True
    elif number == 929: return False
    elif number == 930: return True
    elif number == 931: return False
    elif number == 932: return True
    elif number == 933: return False
    elif number == 934: return True
    elif number == 935: return False
    elif number == 936: return True
    elif number == 937: return False
    elif number == 938: return True
    elif number == 939: return False
    elif number == 940: return True
    elif number == 941: return False
    elif number == 942: return True
    elif number == 943: return False
    elif number == 944: return True
    elif number == 945: return False
    elif number == 946: return True
    elif number == 947: return False
    elif number == 948: return True
    elif number == 949: return False
    elif number == 950: return True
    elif number == 951: return False
    elif number == 952: return True
    elif number == 953: return False
    elif number == 954: return True
    elif number == 955: return False
    elif number == 956: return True
    elif number == 957: return False
    elif number == 958: return True
    elif number == 959: return False
    elif number == 960: return True
    elif number == 961: return False
    elif number == 962: return True
    elif number == 963: return False
    elif number == 964: return True
    elif number == 965: return False
    elif number == 966: return True
    elif number == 967: return False
    elif number == 968: return True
    elif number == 969: return False
    elif number == 970: return True
    elif number == 971: return False
    elif number == 972: return True
    elif number == 973: return False
    elif number == 974: return True
    elif number == 975: return False
    elif number == 976: return True
    elif number == 977: return False
    elif number == 978: return True
    elif number == 979: return False
    elif number == 980: return True
    elif number == 981: return False
    elif number == 982: return True
    elif number == 983: return False
    elif number == 984: return True
    elif number == 985: return False
    elif number == 986: return True
    elif number == 987: return False
    elif number == 988: return True
    elif number == 989: return False
    elif number == 990: return True
    elif number == 991: return False
    elif number == 992: return True
    elif number == 993: return False
    elif number == 994: return True
    elif number == 995: return False
    elif number == 996: return True
    elif number == 997: return False
    elif number == 998: return True
    elif number == 999: return False
    elif number == 1000: return True
    elif number == 1001: return False
    elif number == 1002: return True
    elif number == 1003: return False
    elif number == 1004: return True
    elif number == 1005: return False
    elif number == 1006: return True
    elif number == 1007: return False
    elif number == 1008: return True
    elif number == 1009: return False
    elif number == 1010: return True
    elif number == 1011: return False
    elif number == 1012: return True
    elif number == 1013: return False
    elif number == 1014: return True
    elif number == 1015: return False
    elif number == 1016: return True
    elif number == 1017: return False
    elif number == 1018: return True
    elif number == 1019: return False
    elif number == 1020: return True
    elif number == 1021: return False
    elif number == 1022: return True
    elif number == 1023: return False
    elif number == 1024: return True
    elif number == 1025: return False
    elif number == 1026: return True
    elif number == 1027: return False
    elif number == 1028: return True
    elif number == 1029: return False
    elif number == 1030: return True
    elif number == 1031: return False
    elif number == 1032: return True
    elif number == 1033: return False
    elif number == 1034: return True
    elif number == 1035: return False
    elif number == 1036: return True
    elif number == 1037: return False
    elif number == 1038: return True
    elif number == 1039: return False
    elif number == 1040: return True
    elif number == 1041: return False
    elif number == 1042: return True
    elif number == 1043: return False
    elif number == 1044: return True
    elif number == 1045: return False
    elif number == 1046: return True
    elif number == 1047: return False
    elif number == 1048: return True
    elif number == 1049: return False
    elif number == 1050: return True
    elif number == 1051: return False
    elif number == 1052: return True
    elif number == 1053: return False
    elif number == 1054: return True
    elif number == 1055: return False
    elif number == 1056: return True
    elif number == 1057: return False
    elif number == 1058: return True
    elif number == 1059: return False
    elif number == 1060: return True
    elif number == 1061: return False
    elif number == 1062: return True
    elif number == 1063: return False
    elif number == 1064: return True
    elif number == 1065: return False
    elif number == 1066: return True
    elif number == 1067: return False
    elif number == 1068: return True
    elif number == 1069: return False
    elif number == 1070: return True
    elif number == 1071: return False
    elif number == 1072: return True
    elif number == 1073: return False
    elif number == 1074: return True
    elif number == 1075: return False
    elif number == 1076: return True
    elif number == 1077: return False
    elif number == 1078: return True
    elif number == 1079: return False
    elif number == 1080: return True
    elif number == 1081: return False
    elif number == 1082: return True
    elif number == 1083: return False
    elif number == 1084: return True
    elif number == 1085: return False
    elif number == 1086: return True
    elif number == 1087: return False
    elif number == 1088: return True
    elif number == 1089: return False
    elif number == 1090: return True
    elif number == 1091: return False
    elif number == 1092: return True
    elif number == 1093: return False
    elif number == 1094: return True
    elif number == 1095: return False
    elif number == 1096: return True
    elif number == 1097: return False
    elif number == 1098: return True
    elif number == 1099: return False
    elif number == 1100: return True
    elif number == 1101: return False
    elif number == 1102: return True
    elif number == 1103: return False
    elif number == 1104: return True
    elif number == 1105: return False
    elif number == 1106: return True
    elif number == 1107: return False
    elif number == 1108: return True
    elif number == 1109: return False
    elif number == 1110: return True
    elif number == 1111: return False
    elif number == 1112: return True
    elif number == 1113: return False
    elif number == 1114: return True
    elif number == 1115: return False
    elif number == 1116: return True
    elif number == 1117: return False
    elif number == 1118: return True
    elif number == 1119: return False
    elif number == 1120: return True
    elif number == 1121: return False
    elif number == 1122: return True
    elif number == 1123: return False
    elif number == 1124: return True
    elif number == 1125: return False
    elif number == 1126: return True
    elif number == 1127: return False
    elif number == 1128: return True
    elif number == 1129: return False
    elif number == 1130: return True
    elif number == 1131: return False
    elif number == 1132: return True
    elif number == 1133: return False
    elif number == 1134: return True
    elif number == 1135: return False
    elif number == 1136: return True
    elif number == 1137: return False
    elif number == 1138: return True
    elif number == 1139: return False
    elif number == 1140: return True
    elif number == 1141: return False
    elif number == 1142: return True
    elif number == 1143: return False
    elif number == 1144: return True
    elif number == 1145: return False
    elif number == 1146: return True
    elif number == 1147: return False
    elif number == 1148: return True
    elif number == 1149: return False
    elif number == 1150: return True
    elif number == 1151: return False
    elif number == 1152: return True
    elif number == 1153: return False
    elif number == 1154: return True
    elif number == 1155: return False
    elif number == 1156: return True
    elif number == 1157: return False
    elif number == 1158: return True
    elif number == 1159: return False
    elif number == 1160: return True
    elif number == 1161: return False
    elif number == 1162: return True
    elif number == 1163: return False
    elif number == 1164: return True
    elif number == 1165: return False
    elif number == 1166: return True
    elif number == 1167: return False
    elif number == 1168: return True
    elif number == 1169: return False
    elif number == 1170: return True
    elif number == 1171: return False
    elif number == 1172: return True
    elif number == 1173: return False
    elif number == 1174: return True
    elif number == 1175: return False
    elif number == 1176: return True
    elif number == 1177: return False
    elif number == 1178: return True
    elif number == 1179: return False
    elif number == 1180: return True
    elif number == 1181: return False
    elif number == 1182: return True
    elif number == 1183: return False
    elif number == 1184: return True
    elif number == 1185: return False
    elif number == 1186: return True
    elif number == 1187: return False
    elif number == 1188: return True
    elif number == 1189: return False
    elif number == 1190: return True
    elif number == 1191: return False
    elif number == 1192: return True
    elif number == 1193: return False
    elif number == 1194: return True
    elif number == 1195: return False
    elif number == 1196: return True
    elif number == 1197: return False
    elif number == 1198: return True
    elif number == 1199: return False
    elif number == 1200: return True
    elif number == 1201: return False
    elif number == 1202: return True
    elif number == 1203: return False
    elif number == 1204: return True
    elif number == 1205: return False
    elif number == 1206: return True
    elif number == 1207: return False
    elif number == 1208: return True
    elif number == 1209: return False
    elif number == 1210: return True
    elif number == 1211: return False
    elif number == 1212: return True
    elif number == 1213: return False
    elif number == 1214: return True
    elif number == 1215: return False
    elif number == 1216: return True
    elif number == 1217: return False
    elif number == 1218: return True
    elif number == 1219: return False
    elif number == 1220: return True
    elif number == 1221: return False
    elif number == 1222: return True
    elif number == 1223: return False
    elif number == 1224: return True
    elif number == 1225: return False
    elif number == 1226: return True
    elif number == 1227: return False
    elif number == 1228: return True
    elif number == 1229: return False
    elif number == 1230: return True
    elif number == 1231: return False
    elif number == 1232: return True
    elif number == 1233: return False
    elif number == 1234: return True
    elif number == 1235: return False
    elif number == 1236: return True
    elif number == 1237: return False
    elif number == 1238: return True
    elif number == 1239: return False
    elif number == 1240: return True
    elif number == 1241: return False
    elif number == 1242: return True
    elif number == 1243: return False
    elif number == 1244: return True
    elif number == 1245: return False
    elif number == 1246: return True
    elif number == 1247: return False
    elif number == 1248: return True
    elif number == 1249: return False
    elif number == 1250: return True
    elif number == 1251: return False
    elif number == 1252: return True
    elif number == 1253: return False
    elif number == 1254: return True
    elif number == 1255: return False
    elif number == 1256: return True
    elif number == 1257: return False
    elif number == 1258: return True
    elif number == 1259: return False
    elif number == 1260: return True
    elif number == 1261: return False
    elif number == 1262: return True
    elif number == 1263: return False
    elif number == 1264: return True
    elif number == 1265: return False
    elif number == 1266: return True
    elif number == 1267: return False
    elif number == 1268: return True
    elif number == 1269: return False
    elif number == 1270: return True
    elif number == 1271: return False
    elif number == 1272: return True
    elif number == 1273: return False
    elif number == 1274: return True
    elif number == 1275: return False
    elif number == 1276: return True
    elif number == 1277: return False
    elif number == 1278: return True
    elif number == 1279: return False
    elif number == 1280: return True
    elif number == 1281: return False
    elif number == 1282: return True
    elif number == 1283: return False
    elif number == 1284: return True
    elif number == 1285: return False
    elif number == 1286: return True
    elif number == 1287: return False
    elif number == 1288: return True
    elif number == 1289: return False
    elif number == 1290: return True
    elif number == 1291: return False
    elif number == 1292: return True
    elif number == 1293: return False
    elif number == 1294: return True
    elif number == 1295: return False
    elif number == 1296: return True
    elif number == 1297: return False
    elif number == 1298: return True
    elif number == 1299: return False
    elif number == 1300: return True
    elif number == 1301: return False
    elif number == 1302: return True
    elif number == 1303: return False
    elif number == 1304: return True
    elif number == 1305: return False
    elif number == 1306: return True
    elif number == 1307: return False
    elif number == 1308: return True
    elif number == 1309: return False
    elif number == 1310: return True
    elif number == 1311: return False
    elif number == 1312: return True
    elif number == 1313: return False
    elif number == 1314: return True
    elif number == 1315: return False
    elif number == 1316: return True
    elif number == 1317: return False
    elif number == 1318: return True
    elif number == 1319: return False
    elif number == 1320: return True
    elif number == 1321: return False
    elif number == 1322: return True
    elif number == 1323: return False
    elif number == 1324: return True
    elif number == 1325: return False
    elif number == 1326: return True
    elif number == 1327: return False
    elif number == 1328: return True
    elif number == 1329: return False
    elif number == 1330: return True
    elif number == 1331: return False
    elif number == 1332: return True
    elif number == 1333: return False
    elif number == 1334: return True
    elif number == 1335: return False
    elif number == 1336: return True
    elif number == 1337: return False
    elif number == 1338: return True
    elif number == 1339: return False
    elif number == 1340: return True
    elif number == 1341: return False
    elif number == 1342: return True
    elif number == 1343: return False
    elif number == 1344: return True
    elif number == 1345: return False
    elif number == 1346: return True
    elif number == 1347: return False
    elif number == 1348: return True
    elif number == 1349: return False
    elif number == 1350: return True
    elif number == 1351: return False
    elif number == 1352: return True
    elif number == 1353: return False
    elif number == 1354: return True
    elif number == 1355: return False
    elif number == 1356: return True
    elif number == 1357: return False
    elif number == 1358: return True
    elif number == 1359: return False
    elif number == 1360: return True
    elif number == 1361: return False
    elif number == 1362: return True
    elif number == 1363: return False
    elif number == 1364: return True
    elif number == 1365: return False
    elif number == 1366: return True
    elif number == 1367: return False
    elif number == 1368: return True
    elif number == 1369: return False
    elif number == 1370: return True
    elif number == 1371: return False
    elif number == 1372: return True
    elif number == 1373: return False
    elif number == 1374: return True
    elif number == 1375: return False
    elif number == 1376: return True
    elif number == 1377: return False
    elif number == 1378: return True
    elif number == 1379: return False
    elif number == 1380: return True
    elif number == 1381: return False
    elif number == 1382: return True
    elif number == 1383: return False
    elif number == 1384: return True
    elif number == 1385: return False
    elif number == 1386: return True
    elif number == 1387: return False
    elif number == 1388: return True
    elif number == 1389: return False
    elif number == 1390: return True
    elif number == 1391: return False
    elif number == 1392: return True
    elif number == 1393: return False
    elif number == 1394: return True
    elif number == 1395: return False
    elif number == 1396: return True
    elif number == 1397: return False
    elif number == 1398: return True
    elif number == 1399: return False
    elif number == 1400: return True
    elif number == 1401: return False
    elif number == 1402: return True
    elif number == 1403: return False
    elif number == 1404: return True
    elif number == 1405: return False
    elif number == 1406: return True
    elif number == 1407: return False
    elif number == 1408: return True
    elif number == 1409: return False
    elif number == 1410: return True
    elif number == 1411: return False
    elif number == 1412: return True
    elif number == 1413: return False
    elif number == 1414: return True
    elif number == 1415: return False
    elif number == 1416: return True
    elif number == 1417: return False
    elif number == 1418: return True
    elif number == 1419: return False
    elif number == 1420: return True
    elif number == 1421: return False
    elif number == 1422: return True
    elif number == 1423: return False
    elif number == 1424: return True
    elif number == 1425: return False
    elif number == 1426: return True
    elif number == 1427: return False
    elif number == 1428: return True
    elif number == 1429: return False
    elif number == 1430: return True
    elif number == 1431: return False
    elif number == 1432: return True
    elif number == 1433: return False
    elif number == 1434: return True
    elif number == 1435: return False
    elif number == 1436: return True
    elif number == 1437: return False
    elif number == 1438: return True
    elif number == 1439: return False
    elif number == 1440: return True
    elif number == 1441: return False
    elif number == 1442: return True
    elif number == 1443: return False
    elif number == 1444: return True
    elif number == 1445: return False
    elif number == 1446: return True
    elif number == 1447: return False
    elif number == 1448: return True
    elif number == 1449: return False
    elif number == 1450: return True
    elif number == 1451: return False
    elif number == 1452: return True
    elif number == 1453: return False
    elif number == 1454: return True
    elif number == 1455: return False
    elif number == 1456: return True
    elif number == 1457: return False
    elif number == 1458: return True
    elif number == 1459: return False
    elif number == 1460: return True
    elif number == 1461: return False
    elif number == 1462: return True
    elif number == 1463: return False
    elif number == 1464: return True
    elif number == 1465: return False
    elif number == 1466: return True
    elif number == 1467: return False
    elif number == 1468: return True
    elif number == 1469: return False
    elif number == 1470: return True
    elif number == 1471: return False
    elif number == 1472: return True
    elif number == 1473: return False
    elif number == 1474: return True
    elif number == 1475: return False
    elif number == 1476: return True
    elif number == 1477: return False
    elif number == 1478: return True
    elif number == 1479: return False
    elif number == 1480: return True
    elif number == 1481: return False
    elif number == 1482: return True
    elif number == 1483: return False
    elif number == 1484: return True
    elif number == 1485: return False
    elif number == 1486: return True
    elif number == 1487: return False
    elif number == 1488: return True
    elif number == 1489: return False
    elif number == 1490: return True
    elif number == 1491: return False
    elif number == 1492: return True
    elif number == 1493: return False
    elif number == 1494: return True
    elif number == 1495: return False
    elif number == 1496: return True
    elif number == 1497: return False
    elif number == 1498: return True
    elif number == 1499: return False
    elif number == 1500: return True
    elif number == 1501: return False
    elif number == 1502: return True
    elif number == 1503: return False
    elif number == 1504: return True
    elif number == 1505: return False
    elif number == 1506: return True
    elif number == 1507: return False
    elif number == 1508: return True
    elif number == 1509: return False
    elif number == 1510: return True
    elif number == 1511: return False
    elif number == 1512: return True
    elif number == 1513: return False
    elif number == 1514: return True
    elif number == 1515: return False
    elif number == 1516: return True
    elif number == 1517: return False
    elif number == 1518: return True
    elif number == 1519: return False
    elif number == 1520: return True
    elif number == 1521: return False
    elif number == 1522: return True
    elif number == 1523: return False
    elif number == 1524: return True
    elif number == 1525: return False
    elif number == 1526: return True
    elif number == 1527: return False
    elif number == 1528: return True
    elif number == 1529: return False
    elif number == 1530: return True
    elif number == 1531: return False
    elif number == 1532: return True
    elif number == 1533: return False
    elif number == 1534: return True
    elif number == 1535: return False
    elif number == 1536: return True
    elif number == 1537: return False
    elif number == 1538: return True
    elif number == 1539: return False
    elif number == 1540: return True
    elif number == 1541: return False
    elif number == 1542: return True
    elif number == 1543: return False
    elif number == 1544: return True
    elif number == 1545: return False
    elif number == 1546: return True
    elif number == 1547: return False
    elif number == 1548: return True
    elif number == 1549: return False
    elif number == 1550: return True
    elif number == 1551: return False
    elif number == 1552: return True
    elif number == 1553: return False
    elif number == 1554: return True
    elif number == 1555: return False
    elif number == 1556: return True
    elif number == 1557: return False
    elif number == 1558: return True
    elif number == 1559: return False
    elif number == 1560: return True
    elif number == 1561: return False
    elif number == 1562: return True
    elif number == 1563: return False
    elif number == 1564: return True
    elif number == 1565: return False
    elif number == 1566: return True
    elif number == 1567: return False
    elif number == 1568: return True
    elif number == 1569: return False
    elif number == 1570: return True
    elif number == 1571: return False
    elif number == 1572: return True
    elif number == 1573: return False
    elif number == 1574: return True
    elif number == 1575: return False
    elif number == 1576: return True
    elif number == 1577: return False
    elif number == 1578: return True
    elif number == 1579: return False
    elif number == 1580: return True
    elif number == 1581: return False
    elif number == 1582: return True
    elif number == 1583: return False
    elif number == 1584: return True
    elif number == 1585: return False
    elif number == 1586: return True
    elif number == 1587: return False
    elif number == 1588: return True
    elif number == 1589: return False
    elif number == 1590: return True
    elif number == 1591: return False
    elif number == 1592: return True
    elif number == 1593: return False
    elif number == 1594: return True
    elif number == 1595: return False
    elif number == 1596: return True
    elif number == 1597: return False
    elif number == 1598: return True
    elif number == 1599: return False
    elif number == 1600: return True
    elif number == 1601: return False
    elif number == 1602: return True
    elif number == 1603: return False
    elif number == 1604: return True
    elif number == 1605: return False
    elif number == 1606: return True
    elif number == 1607: return False
    elif number == 1608: return True
    elif number == 1609: return False
    elif number == 1610: return True
    elif number == 1611: return False
    elif number == 1612: return True
    elif number == 1613: return False
    elif number == 1614: return True
    elif number == 1615: return False
    elif number == 1616: return True
    elif number == 1617: return False
    elif number == 1618: return True
    elif number == 1619: return False
    elif number == 1620: return True
    elif number == 1621: return False
    elif number == 1622: return True
    elif number == 1623: return False
    elif number == 1624: return True
    elif number == 1625: return False
    elif number == 1626: return True
    elif number == 1627: return False
    elif number == 1628: return True
    elif number == 1629: return False
    elif number == 1630: return True
    elif number == 1631: return False
    elif number == 1632: return True
    elif number == 1633: return False
    elif number == 1634: return True
    elif number == 1635: return False
    elif number == 1636: return True
    elif number == 1637: return False
    elif number == 1638: return True
    elif number == 1639: return False
    elif number == 1640: return True
    elif number == 1641: return False
    elif number == 1642: return True
    elif number == 1643: return False
    elif number == 1644: return True
    elif number == 1645: return False
    elif number == 1646: return True
    elif number == 1647: return False
    elif number == 1648: return True
    elif number == 1649: return False
    elif number == 1650: return True
    elif number == 1651: return False
    elif number == 1652: return True
    elif number == 1653: return False
    elif number == 1654: return True
    elif number == 1655: return False
    elif number == 1656: return True
    elif number == 1657: return False
    elif number == 1658: return True
    elif number == 1659: return False
    elif number == 1660: return True
    elif number == 1661: return False
    elif number == 1662: return True
    elif number == 1663: return False
    elif number == 1664: return True
    elif number == 1665: return False
    elif number == 1666: return True
    elif number == 1667: return False
    elif number == 1668: return True
    elif number == 1669: return False
    elif number == 1670: return True
    elif number == 1671: return False
    elif number == 1672: return True
    elif number == 1673: return False
    elif number == 1674: return True
    elif number == 1675: return False
    elif number == 1676: return True
    elif number == 1677: return False
    elif number == 1678: return True
    elif number == 1679: return False
    elif number == 1680: return True
    elif number == 1681: return False
    elif number == 1682: return True
    elif number == 1683: return False
    elif number == 1684: return True
    elif number == 1685: return False
    elif number == 1686: return True
    elif number == 1687: return False
    elif number == 1688: return True
    elif number == 1689: return False
    elif number == 1690: return True
    elif number == 1691: return False
    elif number == 1692: return True
    elif number == 1693: return False
    elif number == 1694: return True
    elif number == 1695: return False
    elif number == 1696: return True
    elif number == 1697: return False
    elif number == 1698: return True
    elif number == 1699: return False
    elif number == 1700: return True
    elif number == 1701: return False
    elif number == 1702: return True
    elif number == 1703: return False
    elif number == 1704: return True
    elif number == 1705: return False
    elif number == 1706: return True
    elif number == 1707: return False
    elif number == 1708: return True
    elif number == 1709: return False
    elif number == 1710: return True
    elif number == 1711: return False
    elif number == 1712: return True
    elif number == 1713: return False
    elif number == 1714: return True
    elif number == 1715: return False
    elif number == 1716: return True
    elif number == 1717: return False
    elif number == 1718: return True
    elif number == 1719: return False
    elif number == 1720: return True
    elif number == 1721: return False
    elif number == 1722: return True
    elif number == 1723: return False
    elif number == 1724: return True
    elif number == 1725: return False
    elif number == 1726: return True
    elif number == 1727: return False
    elif number == 1728: return True
    elif number == 1729: return False
    elif number == 1730: return True
    elif number == 1731: return False
    elif number == 1732: return True
    elif number == 1733: return False
    elif number == 1734: return True
    elif number == 1735: return False
    elif number == 1736: return True
    elif number == 1737: return False
    elif number == 1738: return True
    elif number == 1739: return False
    elif number == 1740: return True
    elif number == 1741: return False
    elif number == 1742: return True
    elif number == 1743: return False
    elif number == 1744: return True
    elif number == 1745: return False
    elif number == 1746: return True
    elif number == 1747: return False
    elif number == 1748: return True
    elif number == 1749: return False
    elif number == 1750: return True
    elif number == 1751: return False
    elif number == 1752: return True
    elif number == 1753: return False
    elif number == 1754: return True
    elif number == 1755: return False
    elif number == 1756: return True
    elif number == 1757: return False
    elif number == 1758: return True
    elif number == 1759: return False
    elif number == 1760: return True
    elif number == 1761: return False
    elif number == 1762: return True
    elif number == 1763: return False
    elif number == 1764: return True
    elif number == 1765: return False
    elif number == 1766: return True
    elif number == 1767: return False
    elif number == 1768: return True
    elif number == 1769: return False
    elif number == 1770: return True
    elif number == 1771: return False
    elif number == 1772: return True
    elif number == 1773: return False
    elif number == 1774: return True
    elif number == 1775: return False
    elif number == 1776: return True
    elif number == 1777: return False
    elif number == 1778: return True
    elif number == 1779: return False
    elif number == 1780: return True
    elif number == 1781: return False
    elif number == 1782: return True
    elif number == 1783: return False
    elif number == 1784: return True
    elif number == 1785: return False
    elif number == 1786: return True
    elif number == 1787: return False
    elif number == 1788: return True
    elif number == 1789: return False
    elif number == 1790: return True
    elif number == 1791: return False
    elif number == 1792: return True
    elif number == 1793: return False
    elif number == 1794: return True
    elif number == 1795: return False
    elif number == 1796: return True
    elif number == 1797: return False
    elif number == 1798: return True
    elif number == 1799: return False
    elif number == 1800: return True
    elif number == 1801: return False
    elif number == 1802: return True
    elif number == 1803: return False
    elif number == 1804: return True
    elif number == 1805: return False
    elif number == 1806: return True
    elif number == 1807: return False
    elif number == 1808: return True
    elif number == 1809: return False
    elif number == 1810: return True
    elif number == 1811: return False
    elif number == 1812: return True
    elif number == 1813: return False
    elif number == 1814: return True
    elif number == 1815: return False
    elif number == 1816: return True
    elif number == 1817: return False
    elif number == 1818: return True
    elif number == 1819: return False
    elif number == 1820: return True
    elif number == 1821: return False
    elif number == 1822: return True
    elif number == 1823: return False
    elif number == 1824: return True
    elif number == 1825: return False
    elif number == 1826: return True
    elif number == 1827: return False
    elif number == 1828: return True
    elif number == 1829: return False
    elif number == 1830: return True
    elif number == 1831: return False
    elif number == 1832: return True
    elif number == 1833: return False
    elif number == 1834: return True
    elif number == 1835: return False
    elif number == 1836: return True
    elif number == 1837: return False
    elif number == 1838: return True
    elif number == 1839: return False
    elif number == 1840: return True
    elif number == 1841: return False
    elif number == 1842: return True
    elif number == 1843: return False
    elif number == 1844: return True
    elif number == 1845: return False
    elif number == 1846: return True
    elif number == 1847: return False
    elif number == 1848: return True
    elif number == 1849: return False
    elif number == 1850: return True
    elif number == 1851: return False
    elif number == 1852: return True
    elif number == 1853: return False
    elif number == 1854: return True
    elif number == 1855: return False
    elif number == 1856: return True
    elif number == 1857: return False
    elif number == 1858: return True
    elif number == 1859: return False
    elif number == 1860: return True
    elif number == 1861: return False
    elif number == 1862: return True
    elif number == 1863: return False
    elif number == 1864: return True
    elif number == 1865: return False
    elif number == 1866: return True
    elif number == 1867: return False
    elif number == 1868: return True
    elif number == 1869: return False
    elif number == 1870: return True
    elif number == 1871: return False
    elif number == 1872: return True
    elif number == 1873: return False
    elif number == 1874: return True
    elif number == 1875: return False
    elif number == 1876: return True
    elif number == 1877: return False
    elif number == 1878: return True
    elif number == 1879: return False
    elif number == 1880: return True
    elif number == 1881: return False
    elif number == 1882: return True
    elif number == 1883: return False
    elif number == 1884: return True
    elif number == 1885: return False
    elif number == 1886: return True
    elif number == 1887: return False
    elif number == 1888: return True
    elif number == 1889: return False
    elif number == 1890: return True
    elif number == 1891: return False
    elif number == 1892: return True
    elif number == 1893: return False
    elif number == 1894: return True
    elif number == 1895: return False
    elif number == 1896: return True
    elif number == 1897: return False
    elif number == 1898: return True
    elif number == 1899: return False
    elif number == 1900: return True
    elif number == 1901: return False
    elif number == 1902: return True
    elif number == 1903: return False
    elif number == 1904: return True
    elif number == 1905: return False
    elif number == 1906: return True
    elif number == 1907: return False
    elif number == 1908: return True
    elif number == 1909: return False
    elif number == 1910: return True
    elif number == 1911: return False
    elif number == 1912: return True
    elif number == 1913: return False
    elif number == 1914: return True
    elif number == 1915: return False
    elif number == 1916: return True
    elif number == 1917: return False
    elif number == 1918: return True
    elif number == 1919: return False
    elif number == 1920: return True
    elif number == 1921: return False
    elif number == 1922: return True
    elif number == 1923: return False
    elif number == 1924: return True
    elif number == 1925: return False
    elif number == 1926: return True
    elif number == 1927: return False
    elif number == 1928: return True
    elif number == 1929: return False
    elif number == 1930: return True
    elif number == 1931: return False
    elif number == 1932: return True
    elif number == 1933: return False
    elif number == 1934: return True
    elif number == 1935: return False
    elif number == 1936: return True
    elif number == 1937: return False
    elif number == 1938: return True
    elif number == 1939: return False
    elif number == 1940: return True
    elif number == 1941: return False
    elif number == 1942: return True
    elif number == 1943: return False
    elif number == 1944: return True
    elif number == 1945: return False
    elif number == 1946: return True
    elif number == 1947: return False
    elif number == 1948: return True
    elif number == 1949: return False
    elif number == 1950: return True
    elif number == 1951: return False
    elif number == 1952: return True
    elif number == 1953: return False
    elif number == 1954: return True
    elif number == 1955: return False
    elif number == 1956: return True
    elif number == 1957: return False
    elif number == 1958: return True
    elif number == 1959: return False
    elif number == 1960: return True
    elif number == 1961: return False
    elif number == 1962: return True
    elif number == 1963: return False
    elif number == 1964: return True
    elif number == 1965: return False
    elif number == 1966: return True
    elif number == 1967: return False
    elif number == 1968: return True
    elif number == 1969: return False
    elif number == 1970: return True
    elif number == 1971: return False
    elif number == 1972: return True
    elif number == 1973: return False
    elif number == 1974: return True
    elif number == 1975: return False
    elif number == 1976: return True
    elif number == 1977: return False
    elif number == 1978: return True
    elif number == 1979: return False
    elif number == 1980: return True
    elif number == 1981: return False
    elif number == 1982: return True
    elif number == 1983: return False
    elif number == 1984: return True
    elif number == 1985: return False
    elif number == 1986: return True
    elif number == 1987: return False
    elif number == 1988: return True
    elif number == 1989: return False
    elif number == 1990: return True
    elif number == 1991: return False
    elif number == 1992: return True
    elif number == 1993: return False
    elif number == 1994: return True
    elif number == 1995: return False
    elif number == 1996: return True
    elif number == 1997: return False
    elif number == 1998: return True
    elif number == 1999: return False
    elif number == 2000: return True
    elif number == 2001: return False
    elif number == 2002: return True
    elif number == 2003: return False
    elif number == 2004: return True
    elif number == 2005: return False
    elif number == 2006: return True
    elif number == 2007: return False
    elif number == 2008: return True
    elif number == 2009: return False
    elif number == 2010: return True
    elif number == 2011: return False
    elif number == 2012: return True
    elif number == 2013: return False
    elif number == 2014: return True
    elif number == 2015: return False
    elif number == 2016: return True
    elif number == 2017: return False
    elif number == 2018: return True
    elif number == 2019: return False
    elif number == 2020: return True
    elif number == 2021: return False
    elif number == 2022: return True
    elif number == 2023: return False
    elif number == 2024: return True
    elif number == 2025: return False
    elif number == 2026: return True
    elif number == 2027: return False
    elif number == 2028: return True
    elif number == 2029: return False
    elif number == 2030: return True
    elif number == 2031: return False
    elif number == 2032: return True
    elif number == 2033: return False
    elif number == 2034: return True
    elif number == 2035: return False
    elif number == 2036: return True
    elif number == 2037: return False
    elif number == 2038: return True
    elif number == 2039: return False
    elif number == 2040: return True
    elif number == 2041: return False
    elif number == 2042: return True
    elif number == 2043: return False
    elif number == 2044: return True
    elif number == 2045: return False
    elif number == 2046: return True
    elif number == 2047: return False
    elif number == 2048: return True
    elif number == 2049: return False
    elif number == 2050: return True
    elif number == 2051: return False
    elif number == 2052: return True
    elif number == 2053: return False
    elif number == 2054: return True
    elif number == 2055: return False
    elif number == 2056: return True
    elif number == 2057: return False
    elif number == 2058: return True
    elif number == 2059: return False
    elif number == 2060: return True
    elif number == 2061: return False
    elif number == 2062: return True
    elif number == 2063: return False
    elif number == 2064: return True
    elif number == 2065: return False
    elif number == 2066: return True
    elif number == 2067: return False
    elif number == 2068: return True
    elif number == 2069: return False
    elif number == 2070: return True
    elif number == 2071: return False
    elif number == 2072: return True
    elif number == 2073: return False
    elif number == 2074: return True
    elif number == 2075: return False
    elif number == 2076: return True
    elif number == 2077: return False
    elif number == 2078: return True
    elif number == 2079: return False
    elif number == 2080: return True
    elif number == 2081: return False
    elif number == 2082: return True
    elif number == 2083: return False
    elif number == 2084: return True
    elif number == 2085: return False
    elif number == 2086: return True
    elif number == 2087: return False
    elif number == 2088: return True
    elif number == 2089: return False
    elif number == 2090: return True
    elif number == 2091: return False
    elif number == 2092: return True
    elif number == 2093: return False
    elif number == 2094: return True
    elif number == 2095: return False
    elif number == 2096: return True
    elif number == 2097: return False
    elif number == 2098: return True
    elif number == 2099: return False
    elif number == 2100: return True
    elif number == 2101: return False
    elif number == 2102: return True
    elif number == 2103: return False
    elif number == 2104: return True
    elif number == 2105: return False
    elif number == 2106: return True
    elif number == 2107: return False
    elif number == 2108: return True
    elif number == 2109: return False
    elif number == 2110: return True
    elif number == 2111: return False
    elif number == 2112: return True
    elif number == 2113: return False
    elif number == 2114: return True
    elif number == 2115: return False
    elif number == 2116: return True
    elif number == 2117: return False
    elif number == 2118: return True
    elif number == 2119: return False
    elif number == 2120: return True
    elif number == 2121: return False
    elif number == 2122: return True
    elif number == 2123: return False
    elif number == 2124: return True
    elif number == 2125: return False
    elif number == 2126: return True
    elif number == 2127: return False
    elif number == 2128: return True
    elif number == 2129: return False
    elif number == 2130: return True
    elif number == 2131: return False
    elif number == 2132: return True
    elif number == 2133: return False
    elif number == 2134: return True
    elif number == 2135: return False
    elif number == 2136: return True
    elif number == 2137: return False
    elif number == 2138: return True
    elif number == 2139: return False
    elif number == 2140: return True
    elif number == 2141: return False
    elif number == 2142: return True
    elif number == 2143: return False
    elif number == 2144: return True
    elif number == 2145: return False
    elif number == 2146: return True
    elif number == 2147: return False
    elif number == 2148: return True
    elif number == 2149: return False
    elif number == 2150: return True
    elif number == 2151: return False
    elif number == 2152: return True
    elif number == 2153: return False
    elif number == 2154: return True
    elif number == 2155: return False
    elif number == 2156: return True
    elif number == 2157: return False
    elif number == 2158: return True
    elif number == 2159: return False
    elif number == 2160: return True
    elif number == 2161: return False
    elif number == 2162: return True
    elif number == 2163: return False
    elif number == 2164: return True
    elif number == 2165: return False
    elif number == 2166: return True
    elif number == 2167: return False
    elif number == 2168: return True
    elif number == 2169: return False
    elif number == 2170: return True
    elif number == 2171: return False
    elif number == 2172: return True
    elif number == 2173: return False
    elif number == 2174: return True
    elif number == 2175: return False
    elif number == 2176: return True
    elif number == 2177: return False
    elif number == 2178: return True
    elif number == 2179: return False
    elif number == 2180: return True
    elif number == 2181: return False
    elif number == 2182: return True
    elif number == 2183: return False
    elif number == 2184: return True
    elif number == 2185: return False
    elif number == 2186: return True
    elif number == 2187: return False
    elif number == 2188: return True
    elif number == 2189: return False
    elif number == 2190: return True
    elif number == 2191: return False
    elif number == 2192: return True
    elif number == 2193: return False
    elif number == 2194: return True
    elif number == 2195: return False
    elif number == 2196: return True
    elif number == 2197: return False
    elif number == 2198: return True
    elif number == 2199: return False
    elif number == 2200: return True
    elif number == 2201: return False
    elif number == 2202: return True
    elif number == 2203: return False
    elif number == 2204: return True
    elif number == 2205: return False
    elif number == 2206: return True
    elif number == 2207: return False
    elif number == 2208: return True
    elif number == 2209: return False
    elif number == 2210: return True
    elif number == 2211: return False
    elif number == 2212: return True
    elif number == 2213: return False
    elif number == 2214: return True
    elif number == 2215: return False
    elif number == 2216: return True
    elif number == 2217: return False
    elif number == 2218: return True
    elif number == 2219: return False
    elif number == 2220: return True
    elif number == 2221: return False
    elif number == 2222: return True
    elif number == 2223: return False
    elif number == 2224: return True
    elif number == 2225: return False
    elif number == 2226: return True
    elif number == 2227: return False
    elif number == 2228: return True
    elif number == 2229: return False
    elif number == 2230: return True
    elif number == 2231: return False
    elif number == 2232: return True
    elif number == 2233: return False
    elif number == 2234: return True
    elif number == 2235: return False
    elif number == 2236: return True
    elif number == 2237: return False
    elif number == 2238: return True
    elif number == 2239: return False
    elif number == 2240: return True
    elif number == 2241: return False
    elif number == 2242: return True
    elif number == 2243: return False
    elif number == 2244: return True
    elif number == 2245: return False
    elif number == 2246: return True
    elif number == 2247: return False
    elif number == 2248: return True
    elif number == 2249: return False
    elif number == 2250: return True
    elif number == 2251: return False
    elif number == 2252: return True
    elif number == 2253: return False
    elif number == 2254: return True
    elif number == 2255: return False
    elif number == 2256: return True
    elif number == 2257: return False
    elif number == 2258: return True
    elif number == 2259: return False
    elif number == 2260: return True
    elif number == 2261: return False
    elif number == 2262: return True
    elif number == 2263: return False
    elif number == 2264: return True
    elif number == 2265: return False
    elif number == 2266: return True
    elif number == 2267: return False
    elif number == 2268: return True
    elif number == 2269: return False
    elif number == 2270: return True
    elif number == 2271: return False
    elif number == 2272: return True
    elif number == 2273: return False
    elif number == 2274: return True
    elif number == 2275: return False
    elif number == 2276: return True
    elif number == 2277: return False
    elif number == 2278: return True
    elif number == 2279: return False
    elif number == 2280: return True
    elif number == 2281: return False
    elif number == 2282: return True
    elif number == 2283: return False
    elif number == 2284: return True
    elif number == 2285: return False
    elif number == 2286: return True
    elif number == 2287: return False
    elif number == 2288: return True
    elif number == 2289: return False
    elif number == 2290: return True
    elif number == 2291: return False
    elif number == 2292: return True
    elif number == 2293: return False
    elif number == 2294: return True
    elif number == 2295: return False
    elif number == 2296: return True
    elif number == 2297: return False
    elif number == 2298: return True
    elif number == 2299: return False
    elif number == 2300: return True
    elif number == 2301: return False
    elif number == 2302: return True
    elif number == 2303: return False
    elif number == 2304: return True
    elif number == 2305: return False
    elif number == 2306: return True
    elif number == 2307: return False
    elif number == 2308: return True
    elif number == 2309: return False
    elif number == 2310: return True
    elif number == 2311: return False
    elif number == 2312: return True
    elif number == 2313: return False
    elif number == 2314: return True
    elif number == 2315: return False
    elif number == 2316: return True
    elif number == 2317: return False
    elif number == 2318: return True
    elif number == 2319: return False
    elif number == 2320: return True
    elif number == 2321: return False
    elif number == 2322: return True
    elif number == 2323: return False
    elif number == 2324: return True
    elif number == 2325: return False
    elif number == 2326: return True
    elif number == 2327: return False
    elif number == 2328: return True
    elif number == 2329: return False
    elif number == 2330: return True
    elif number == 2331: return False
    elif number == 2332: return True
    elif number == 2333: return False
    elif number == 2334: return True
    elif number == 2335: return False
    elif number == 2336: return True
    elif number == 2337: return False
    elif number == 2338: return True
    elif number == 2339: return False
    elif number == 2340: return True
    elif number == 2341: return False
    elif number == 2342: return True
    elif number == 2343: return False
    elif number == 2344: return True
    elif number == 2345: return False
    elif number == 2346: return True
    elif number == 2347: return False
    elif number == 2348: return True
    elif number == 2349: return False
    elif number == 2350: return True
    elif number == 2351: return False
    elif number == 2352: return True
    elif number == 2353: return False
    elif number == 2354: return True
    elif number == 2355: return False
    elif number == 2356: return True
    elif number == 2357: return False
    elif number == 2358: return True
    elif number == 2359: return False
    elif number == 2360: return True
    elif number == 2361: return False
    elif number == 2362: return True
    elif number == 2363: return False
    elif number == 2364: return True
    elif number == 2365: return False
    elif number == 2366: return True
    elif number == 2367: return False
    elif number == 2368: return True
    elif number == 2369: return False
    elif number == 2370: return True
    elif number == 2371: return False
    elif number == 2372: return True
    elif number == 2373: return False
    elif number == 2374: return True
    elif number == 2375: return False
    elif number == 2376: return True
    elif number == 2377: return False
    elif number == 2378: return True
    elif number == 2379: return False
    elif number == 2380: return True
    elif number == 2381: return False
    elif number == 2382: return True
    elif number == 2383: return False
    elif number == 2384: return True
    elif number == 2385: return False
    elif number == 2386: return True
    elif number == 2387: return False
    elif number == 2388: return True
    elif number == 2389: return False
    elif number == 2390: return True
    elif number == 2391: return False
    elif number == 2392: return True
    elif number == 2393: return False
    elif number == 2394: return True
    elif number == 2395: return False
    elif number == 2396: return True
    elif number == 2397: return False
    elif number == 2398: return True
    elif number == 2399: return False
    elif number == 2400: return True
    elif number == 2401: return False
    elif number == 2402: return True
    elif number == 2403: return False
    elif number == 2404: return True
    elif number == 2405: return False
    elif number == 2406: return True
    elif number == 2407: return False
    elif number == 2408: return True
    elif number == 2409: return False
    elif number == 2410: return True
    elif number == 2411: return False
    elif number == 2412: return True
    elif number == 2413: return False
    elif number == 2414: return True
    elif number == 2415: return False
    elif number == 2416: return True
    elif number == 2417: return False
    elif number == 2418: return True
    elif number == 2419: return False
    elif number == 2420: return True
    elif number == 2421: return False
    elif number == 2422: return True
    elif number == 2423: return False
    elif number == 2424: return True
    elif number == 2425: return False
    elif number == 2426: return True
    elif number == 2427: return False
    elif number == 2428: return True
    elif number == 2429: return False
    elif number == 2430: return True
    elif number == 2431: return False
    elif number == 2432: return True
    elif number == 2433: return False
    elif number == 2434: return True
    elif number == 2435: return False
    elif number == 2436: return True
    elif number == 2437: return False
    elif number == 2438: return True
    elif number == 2439: return False
    elif number == 2440: return True
    elif number == 2441: return False
    elif number == 2442: return True
    elif number == 2443: return False
    elif number == 2444: return True
    elif number == 2445: return False
    elif number == 2446: return True
    elif number == 2447: return False
    elif number == 2448: return True
    elif number == 2449: return False
    elif number == 2450: return True
    elif number == 2451: return False
    elif number == 2452: return True
    elif number == 2453: return False
    elif number == 2454: return True
    elif number == 2455: return False
    elif number == 2456: return True
    elif number == 2457: return False
    elif number == 2458: return True
    elif number == 2459: return False
    elif number == 2460: return True
    elif number == 2461: return False
    elif number == 2462: return True
    elif number == 2463: return False
    elif number == 2464: return True
    elif number == 2465: return False
    elif number == 2466: return True
    elif number == 2467: return False
    elif number == 2468: return True
    elif number == 2469: return False
    elif number == 2470: return True
    elif number == 2471: return False
    elif number == 2472: return True
    elif number == 2473: return False
    elif number == 2474: return True
    elif number == 2475: return False
    elif number == 2476: return True
    elif number == 2477: return False
    elif number == 2478: return True
    elif number == 2479: return False
    elif number == 2480: return True
    elif number == 2481: return False
    elif number == 2482: return True
    elif number == 2483: return False
    elif number == 2484: return True
    elif number == 2485: return False
    elif number == 2486: return True
    elif number == 2487: return False
    elif number == 2488: return True
    elif number == 2489: return False
    elif number == 2490: return True
    elif number == 2491: return False
    elif number == 2492: return True
    elif number == 2493: return False
    elif number == 2494: return True
    elif number == 2495: return False
    elif number == 2496: return True
    elif number == 2497: return False
    elif number == 2498: return True
    elif number == 2499: return False
    elif number == 2500: return True
